version: '3.9'

services:
  api:
    image: ghcr.io/luis782006/academianovit:latest
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING_FILE: /run/secrets/db_connection_string
    secrets:
      - db_connection_string
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tivon1234
      POSTGRES_DB: datos
    volumes:
      - postgres_data:/var/lib/postgresql/data

secrets:
  db_connection_string:
    file: ./secrets/db_connection_string.txt

volumes:
  postgres_data: