version: '3.8'

services:
  webapi:
    # IMPORTANTE: Reemplaza 'YOUR_GITHUB_USERNAME' con tu nombre de usuario de GitHub.
    image: ghcr.io/YOUR_GITHUB_USERNAME/academianovit2025/academianovit:main
    ports:
      # Mapea el puerto 5286 del host al puerto 8080 del contenedor (HTTP)
      - "5286:8080"
      # Mapea el puerto 7280 del host al puerto 8081 del contenedor (HTTPS)
      - "7280:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${{ secrets.DB_CONNECTION_STRING }}
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
