version: '3.9'

services:
  postgres:
    container_name: postgres_db
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tivon1234
    ports:
      - "5432:5432"

  AppDocker:
    container_name: appdocker
    depends_on:
      - postgres
    image: ghcr.io/luis782006/appdocker:latest
    ports:
      - "8080:5000"
    environment:
      DB_CONNECTION_STRING_FILE: /run/secrets/db_connection_string
    secrets:
      - db_connection_string

secrets:
  db_connection_string:
    file: ./secrets/db_connection_string.txt