#Nombre del workflow
name: GH-build-DEV

# eventos disparadores 
on:
  push:
    branches: [ "main" ] # el evento/s que hace disparar el workflow

jobs:
  build:
    runs-on: ubuntu-24.04 # Dejar explicito el sistema operativo, su version
    steps:
    - uses: actions/checkout@v4 # Clonar el repositorio en el runner
    #Nombre del paso: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: | # 8.0.x son versiones LTS
            8.0.x  
            9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal